// Mocks generated by Mockito 5.4.6 from annotations
// in dentaltid/test/features/appointments/appointment_service_finance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dentaltid/src/features/appointments/data/appointment_repository.dart'
    as _i3;
import 'package:dentaltid/src/features/appointments/domain/appointment.dart'
    as _i2;
import 'package:dentaltid/src/features/appointments/domain/appointment_status.dart'
    as _i5;
import 'package:dentaltid/src/features/finance/application/finance_service.dart'
    as _i8;
import 'package:dentaltid/src/features/finance/domain/transaction.dart' as _i9;
import 'package:dentaltid/src/features/security/application/audit_service.dart'
    as _i6;
import 'package:dentaltid/src/features/security/domain/audit_event.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppointment_0 extends _i1.SmartFake implements _i2.Appointment {
  _FakeAppointment_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppointmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentRepository extends _i1.Mock
    implements _i3.AppointmentRepository {
  MockAppointmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Appointment> createAppointment(_i2.Appointment? appointment) =>
      (super.noSuchMethod(
            Invocation.method(#createAppointment, [appointment]),
            returnValue: _i4.Future<_i2.Appointment>.value(
              _FakeAppointment_0(
                this,
                Invocation.method(#createAppointment, [appointment]),
              ),
            ),
          )
          as _i4.Future<_i2.Appointment>);

  @override
  _i4.Future<List<_i2.Appointment>> getAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getAppointments, []),
            returnValue: _i4.Future<List<_i2.Appointment>>.value(
              <_i2.Appointment>[],
            ),
          )
          as _i4.Future<List<_i2.Appointment>>);

  @override
  _i4.Future<void> updateAppointment(_i2.Appointment? appointment) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppointment, [appointment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAppointment(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppointment, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Appointment>> getUpcomingAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingAppointments, []),
            returnValue: _i4.Future<List<_i2.Appointment>>.value(
              <_i2.Appointment>[],
            ),
          )
          as _i4.Future<List<_i2.Appointment>>);

  @override
  _i4.Future<_i2.Appointment?> getAppointmentByPatientAndDateTime(
    int? patientId,
    DateTime? dateTime,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentByPatientAndDateTime, [
              patientId,
              dateTime,
            ]),
            returnValue: _i4.Future<_i2.Appointment?>.value(),
          )
          as _i4.Future<_i2.Appointment?>);

  @override
  _i4.Future<void> updateAppointmentStatus(
    int? id,
    _i5.AppointmentStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppointmentStatus, [id, status]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Appointment>> getAppointmentsByStatusForDate(
    DateTime? dateTime,
    _i5.AppointmentStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentsByStatusForDate, [
              dateTime,
              status,
            ]),
            returnValue: _i4.Future<List<_i2.Appointment>>.value(
              <_i2.Appointment>[],
            ),
          )
          as _i4.Future<List<_i2.Appointment>>);

  @override
  _i4.Future<List<_i2.Appointment>> getTodaysAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysAppointments, []),
            returnValue: _i4.Future<List<_i2.Appointment>>.value(
              <_i2.Appointment>[],
            ),
          )
          as _i4.Future<List<_i2.Appointment>>);

  @override
  _i4.Future<List<_i2.Appointment>> getTodaysAppointmentsForEmergencyPatients(
    List<int>? emergencyPatientIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysAppointmentsForEmergencyPatients, [
              emergencyPatientIds,
            ]),
            returnValue: _i4.Future<List<_i2.Appointment>>.value(
              <_i2.Appointment>[],
            ),
          )
          as _i4.Future<List<_i2.Appointment>>);

  @override
  _i4.Future<List<_i2.Appointment>> getAppointmentsForPatient(int? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentsForPatient, [patientId]),
            returnValue: _i4.Future<List<_i2.Appointment>>.value(
              <_i2.Appointment>[],
            ),
          )
          as _i4.Future<List<_i2.Appointment>>);
}

/// A class which mocks [AuditService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuditService extends _i1.Mock implements _i6.AuditService {
  MockAuditService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> logEvent(_i7.AuditAction? action, {String? details}) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [action], {#details: details}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.AuditEvent>> getAuditEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getAuditEvents, []),
            returnValue: _i4.Future<List<_i7.AuditEvent>>.value(
              <_i7.AuditEvent>[],
            ),
          )
          as _i4.Future<List<_i7.AuditEvent>>);
}

/// A class which mocks [FinanceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFinanceService extends _i1.Mock implements _i8.FinanceService {
  MockFinanceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i9.Transaction>> getAdjustedTransactionsFiltered({
    required DateTime? startDate,
    required DateTime? endDate,
    Set<_i9.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAdjustedTransactionsFiltered, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includedSourceTypes: includedSourceTypes,
            }),
            returnValue: _i4.Future<List<_i9.Transaction>>.value(
              <_i9.Transaction>[],
            ),
          )
          as _i4.Future<List<_i9.Transaction>>);

  @override
  _i4.Future<void> addTransaction(
    _i9.Transaction? transaction, {
    bool? invalidate = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addTransaction,
              [transaction],
              {#invalidate: invalidate},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.Transaction>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i4.Future<List<_i9.Transaction>>.value(
              <_i9.Transaction>[],
            ),
          )
          as _i4.Future<List<_i9.Transaction>>);

  @override
  _i4.Future<void> updateTransaction(
    _i9.Transaction? transaction, {
    bool? invalidate = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTransaction,
              [transaction],
              {#invalidate: invalidate},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.Transaction>> getTransactionsBySessionId(
    int? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsBySessionId, [sessionId]),
            returnValue: _i4.Future<List<_i9.Transaction>>.value(
              <_i9.Transaction>[],
            ),
          )
          as _i4.Future<List<_i9.Transaction>>);

  @override
  _i4.Future<String> getPaymentStatusForAppointment(int? appointmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentStatusForAppointment, [appointmentId]),
            returnValue: _i4.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getPaymentStatusForAppointment, [
                  appointmentId,
                ]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<List<_i9.Transaction>> getTransactionsFiltered({
    DateTime? startDate,
    DateTime? endDate,
    Set<_i9.TransactionSourceType>? includedSourceTypes,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsFiltered, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includedSourceTypes: includedSourceTypes,
              #category: category,
            }),
            returnValue: _i4.Future<List<_i9.Transaction>>.value(
              <_i9.Transaction>[],
            ),
          )
          as _i4.Future<List<_i9.Transaction>>);

  @override
  _i4.Future<Map<String, double>> getSummary(
    DateTime? date,
    String? period, {
    Set<String>? includedCategories,
    Set<_i9.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSummary,
              [date, period],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i4.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<Map<String, double>> getDailySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i9.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDailySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i4.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<Map<String, double>> getWeeklySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i9.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getWeeklySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i4.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<Map<String, double>> getMonthlySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i9.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMonthlySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i4.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<Map<String, double>> getYearlySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i9.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getYearlySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i4.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<List<_i9.Transaction>> getTransactionsForChart({
    DateTime? startDate,
    DateTime? endDate,
    Set<_i9.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsForChart, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includedSourceTypes: includedSourceTypes,
            }),
            returnValue: _i4.Future<List<_i9.Transaction>>.value(
              <_i9.Transaction>[],
            ),
          )
          as _i4.Future<List<_i9.Transaction>>);
}
