// Mocks generated by Mockito 5.4.6 from annotations
// in dentaltid/test/features/inventory/inventory_service_finance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dentaltid/src/features/finance/application/finance_service.dart'
    as _i7;
import 'package:dentaltid/src/features/finance/domain/transaction.dart' as _i8;
import 'package:dentaltid/src/features/inventory/data/inventory_repository.dart'
    as _i3;
import 'package:dentaltid/src/features/inventory/domain/inventory_item.dart'
    as _i2;
import 'package:dentaltid/src/features/security/application/audit_service.dart'
    as _i5;
import 'package:dentaltid/src/features/security/domain/audit_event.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInventoryItem_0 extends _i1.SmartFake implements _i2.InventoryItem {
  _FakeInventoryItem_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i3.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.InventoryItem> createInventoryItem(_i2.InventoryItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#createInventoryItem, [item]),
            returnValue: _i4.Future<_i2.InventoryItem>.value(
              _FakeInventoryItem_0(
                this,
                Invocation.method(#createInventoryItem, [item]),
              ),
            ),
          )
          as _i4.Future<_i2.InventoryItem>);

  @override
  _i4.Future<List<_i2.InventoryItem>> getInventoryItems() =>
      (super.noSuchMethod(
            Invocation.method(#getInventoryItems, []),
            returnValue: _i4.Future<List<_i2.InventoryItem>>.value(
              <_i2.InventoryItem>[],
            ),
          )
          as _i4.Future<List<_i2.InventoryItem>>);

  @override
  _i4.Future<void> updateInventoryItem(_i2.InventoryItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateInventoryItem, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteInventoryItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInventoryItem, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.InventoryItem?> getInventoryItemById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getInventoryItemById, [id]),
            returnValue: _i4.Future<_i2.InventoryItem?>.value(),
          )
          as _i4.Future<_i2.InventoryItem?>);
}

/// A class which mocks [AuditService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuditService extends _i1.Mock implements _i5.AuditService {
  MockAuditService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> logEvent(_i6.AuditAction? action, {String? details}) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [action], {#details: details}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.AuditEvent>> getAuditEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getAuditEvents, []),
            returnValue: _i4.Future<List<_i6.AuditEvent>>.value(
              <_i6.AuditEvent>[],
            ),
          )
          as _i4.Future<List<_i6.AuditEvent>>);
}

/// A class which mocks [FinanceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFinanceService extends _i1.Mock implements _i7.FinanceService {
  MockFinanceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i8.Transaction>> getAdjustedTransactionsFiltered({
    required DateTime? startDate,
    required DateTime? endDate,
    Set<_i8.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAdjustedTransactionsFiltered, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includedSourceTypes: includedSourceTypes,
            }),
            returnValue: _i4.Future<List<_i8.Transaction>>.value(
              <_i8.Transaction>[],
            ),
          )
          as _i4.Future<List<_i8.Transaction>>);

  @override
  _i4.Future<void> addTransaction(
    _i8.Transaction? transaction, {
    bool? invalidate = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addTransaction,
              [transaction],
              {#invalidate: invalidate},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.Transaction>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i4.Future<List<_i8.Transaction>>.value(
              <_i8.Transaction>[],
            ),
          )
          as _i4.Future<List<_i8.Transaction>>);

  @override
  _i4.Future<void> updateTransaction(
    _i8.Transaction? transaction, {
    bool? invalidate = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTransaction,
              [transaction],
              {#invalidate: invalidate},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.Transaction>> getTransactionsBySessionId(
    int? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsBySessionId, [sessionId]),
            returnValue: _i4.Future<List<_i8.Transaction>>.value(
              <_i8.Transaction>[],
            ),
          )
          as _i4.Future<List<_i8.Transaction>>);

  @override
  _i4.Future<String> getPaymentStatusForAppointment(int? appointmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentStatusForAppointment, [appointmentId]),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getPaymentStatusForAppointment, [
                  appointmentId,
                ]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<List<_i8.Transaction>> getTransactionsFiltered({
    DateTime? startDate,
    DateTime? endDate,
    Set<_i8.TransactionSourceType>? includedSourceTypes,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsFiltered, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includedSourceTypes: includedSourceTypes,
              #category: category,
            }),
            returnValue: _i4.Future<List<_i8.Transaction>>.value(
              <_i8.Transaction>[],
            ),
          )
          as _i4.Future<List<_i8.Transaction>>);

  @override
  _i4.Future<Map<String, double>> getSummary(
    DateTime? date,
    String? period, {
    Set<String>? includedCategories,
    Set<_i8.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSummary,
              [date, period],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i4.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<Map<String, double>> getDailySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i8.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDailySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i4.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<Map<String, double>> getWeeklySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i8.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getWeeklySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i4.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<Map<String, double>> getMonthlySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i8.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMonthlySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i4.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<Map<String, double>> getYearlySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i8.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getYearlySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i4.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i4.Future<Map<String, double>>);

  @override
  _i4.Future<List<_i8.Transaction>> getTransactionsForChart({
    DateTime? startDate,
    DateTime? endDate,
    Set<_i8.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsForChart, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includedSourceTypes: includedSourceTypes,
            }),
            returnValue: _i4.Future<List<_i8.Transaction>>.value(
              <_i8.Transaction>[],
            ),
          )
          as _i4.Future<List<_i8.Transaction>>);
}
