// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfhx8YrFmLXv1UpSQ4ViThfNrmnk7hV-E',
    appId: '1:698475695605:ios:be2911cb400524103964bc',
    messagingSenderId: '698475695605',
    projectId: 'dentaltid',
    storageBucket: 'dentaltid.firebasestorage.app',
    iosBundleId: 'com.example.dentaltid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqW_c9YRyxM8GnICR9kSRvs1T-GhseZzY',
    appId: '1:698475695605:web:1e576e008f891e543964bc',
    messagingSenderId: '698475695605',
    projectId: 'dentaltid',
    authDomain: 'dentaltid.firebaseapp.com',
    storageBucket: 'dentaltid.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-am4DCNkJ6QKEgWhWL3M0YJkK3bpBxQ',
    appId: '1:698475695605:android:d2e9bec87abae2ef3964bc',
    messagingSenderId: '698475695605',
    projectId: 'dentaltid',
    storageBucket: 'dentaltid.firebasestorage.app',
  );

}