// Mocks generated by Mockito 5.4.6 from annotations
// in dentaltid/test/features/finance/finance_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dentaltid/src/features/finance/data/finance_repository.dart'
    as _i2;
import 'package:dentaltid/src/features/finance/data/recurring_charge_repository.dart'
    as _i5;
import 'package:dentaltid/src/features/finance/domain/recurring_charge.dart'
    as _i6;
import 'package:dentaltid/src/features/finance/domain/transaction.dart' as _i4;
import 'package:dentaltid/src/features/security/application/audit_service.dart'
    as _i7;
import 'package:dentaltid/src/features/security/domain/audit_event.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FinanceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFinanceRepository extends _i1.Mock implements _i2.FinanceRepository {
  MockFinanceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createTransaction(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTransaction(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Transaction>> getTransactionsFiltered({
    DateTime? startDate,
    DateTime? endDate,
    Set<_i4.TransactionSourceType>? includedSourceTypes,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsFiltered, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includedSourceTypes: includedSourceTypes,
              #category: category,
            }),
            returnValue: _i3.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<List<_i4.Transaction>> getTransactionsBySessionId(
    int? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsBySessionId, [sessionId]),
            returnValue: _i3.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i3.Future<List<_i4.Transaction>>);
}

/// A class which mocks [RecurringChargeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecurringChargeRepository extends _i1.Mock
    implements _i5.RecurringChargeRepository {
  MockRecurringChargeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createRecurringCharge(
    _i6.RecurringCharge? recurringCharge,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRecurringCharge, [recurringCharge]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.RecurringCharge>> getAllRecurringCharges() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecurringCharges, []),
            returnValue: _i3.Future<List<_i6.RecurringCharge>>.value(
              <_i6.RecurringCharge>[],
            ),
          )
          as _i3.Future<List<_i6.RecurringCharge>>);

  @override
  _i3.Future<_i6.RecurringCharge?> getRecurringChargeById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecurringChargeById, [id]),
            returnValue: _i3.Future<_i6.RecurringCharge?>.value(),
          )
          as _i3.Future<_i6.RecurringCharge?>);

  @override
  _i3.Future<void> updateRecurringCharge(
    _i6.RecurringCharge? recurringCharge,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecurringCharge, [recurringCharge]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRecurringCharge(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecurringCharge, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AuditService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuditService extends _i1.Mock implements _i7.AuditService {
  MockAuditService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> logEvent(_i8.AuditAction? action, {String? details}) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [action], {#details: details}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.AuditEvent>> getAuditEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getAuditEvents, []),
            returnValue: _i3.Future<List<_i8.AuditEvent>>.value(
              <_i8.AuditEvent>[],
            ),
          )
          as _i3.Future<List<_i8.AuditEvent>>);
}
