// Mocks generated by Mockito 5.4.6 from annotations
// in dentaltid/test/features/finance/recurring_charges_screen_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dentaltid/src/features/finance/application/recurring_charge_service.dart'
    as _i2;
import 'package:dentaltid/src/features/finance/domain/recurring_charge.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RecurringChargeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecurringChargeService extends _i1.Mock
    implements _i2.RecurringChargeService {
  MockRecurringChargeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addRecurringCharge(_i4.RecurringCharge? recurringCharge) =>
      (super.noSuchMethod(
            Invocation.method(#addRecurringCharge, [recurringCharge]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.RecurringCharge>> getAllRecurringCharges() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecurringCharges, []),
            returnValue: _i3.Future<List<_i4.RecurringCharge>>.value(
              <_i4.RecurringCharge>[],
            ),
          )
          as _i3.Future<List<_i4.RecurringCharge>>);

  @override
  _i3.Future<void> updateRecurringCharge(
    _i4.RecurringCharge? recurringCharge,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecurringCharge, [recurringCharge]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRecurringCharge(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecurringCharge, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> generateTransactionsForRecurringCharges(
    DateTime? periodStart,
    DateTime? periodEnd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateTransactionsForRecurringCharges, [
              periodStart,
              periodEnd,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
