// Mocks generated by Mockito 5.4.6 from annotations
// in dentaltid/test/features/finance/recurring_charge_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dentaltid/src/features/finance/application/finance_service.dart'
    as _i5;
import 'package:dentaltid/src/features/finance/data/recurring_charge_repository.dart'
    as _i2;
import 'package:dentaltid/src/features/finance/domain/recurring_charge.dart'
    as _i4;
import 'package:dentaltid/src/features/finance/domain/transaction.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RecurringChargeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecurringChargeRepository extends _i1.Mock
    implements _i2.RecurringChargeRepository {
  MockRecurringChargeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createRecurringCharge(
    _i4.RecurringCharge? recurringCharge,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRecurringCharge, [recurringCharge]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.RecurringCharge>> getAllRecurringCharges() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecurringCharges, []),
            returnValue: _i3.Future<List<_i4.RecurringCharge>>.value(
              <_i4.RecurringCharge>[],
            ),
          )
          as _i3.Future<List<_i4.RecurringCharge>>);

  @override
  _i3.Future<_i4.RecurringCharge?> getRecurringChargeById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecurringChargeById, [id]),
            returnValue: _i3.Future<_i4.RecurringCharge?>.value(),
          )
          as _i3.Future<_i4.RecurringCharge?>);

  @override
  _i3.Future<void> updateRecurringCharge(
    _i4.RecurringCharge? recurringCharge,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecurringCharge, [recurringCharge]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRecurringCharge(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecurringCharge, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [FinanceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFinanceService extends _i1.Mock implements _i5.FinanceService {
  MockFinanceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.Transaction>> getAdjustedTransactionsFiltered({
    required DateTime? startDate,
    required DateTime? endDate,
    Set<_i6.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAdjustedTransactionsFiltered, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includedSourceTypes: includedSourceTypes,
            }),
            returnValue: _i3.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i3.Future<List<_i6.Transaction>>);

  @override
  _i3.Future<void> addTransaction(
    _i6.Transaction? transaction, {
    bool? invalidate = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addTransaction,
              [transaction],
              {#invalidate: invalidate},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.Transaction>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i3.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i3.Future<List<_i6.Transaction>>);

  @override
  _i3.Future<void> updateTransaction(
    _i6.Transaction? transaction, {
    bool? invalidate = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTransaction,
              [transaction],
              {#invalidate: invalidate},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.Transaction>> getTransactionsBySessionId(
    int? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsBySessionId, [sessionId]),
            returnValue: _i3.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i3.Future<List<_i6.Transaction>>);

  @override
  _i3.Future<String> getPaymentStatusForAppointment(int? appointmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentStatusForAppointment, [appointmentId]),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getPaymentStatusForAppointment, [
                  appointmentId,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<_i6.Transaction>> getTransactionsFiltered({
    DateTime? startDate,
    DateTime? endDate,
    Set<_i6.TransactionSourceType>? includedSourceTypes,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsFiltered, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includedSourceTypes: includedSourceTypes,
              #category: category,
            }),
            returnValue: _i3.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i3.Future<List<_i6.Transaction>>);

  @override
  _i3.Future<Map<String, double>> getSummary(
    DateTime? date,
    String? period, {
    Set<String>? includedCategories,
    Set<_i6.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSummary,
              [date, period],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<Map<String, double>> getDailySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i6.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDailySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<Map<String, double>> getWeeklySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i6.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getWeeklySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<Map<String, double>> getMonthlySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i6.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMonthlySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<Map<String, double>> getYearlySummary(
    DateTime? date, {
    Set<String>? includedCategories,
    Set<_i6.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getYearlySummary,
              [date],
              {
                #includedCategories: includedCategories,
                #includedSourceTypes: includedSourceTypes,
              },
            ),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<List<_i6.Transaction>> getTransactionsForChart({
    DateTime? startDate,
    DateTime? endDate,
    Set<_i6.TransactionSourceType>? includedSourceTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsForChart, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includedSourceTypes: includedSourceTypes,
            }),
            returnValue: _i3.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i3.Future<List<_i6.Transaction>>);
}
